### ISSUE TITLE
bulkblocks fail to insert block due to dataset concurrent insert

### ISSUE THREAD

**Issue by amaltaro** [dmwm/DBS#490] opened 2015-09-24 13:40 UTC
Yuyi :-)

I also just caught 2 errors in our DBS3Upload component when inserting blocks, here is the traceback
```
2015-09-24 13:59:01,872:INFO:DBSUploadPoller:About to insert block /RelValProdMinBias/CMSSW_7_0_0_pre11-DIGIPROD1_TaskChain_MC_HG1510_Validation_TEST_Alan_v1-v1/AODSIM#7ac1b1a2-62b2-11e5-a863-02163e006e3e
2015-09-24 13:59:01,875:INFO:DBSUploadPoller:About to insert block /RelValProdMinBias/CMSSW_7_0_0_pre11-DIGIPROD1_TaskChain_MC_HG1510_Validation_TEST_Alan_v1-v1/GEN-SIM-RECO#7abeb498-62b2-11e5-a863-02163e006e3e
2015-09-24 13:59:02,191:ERROR:DBSUploadPoller:Error trying to process block /RelValProdMinBias/CMSSW_7_0_0_pre11-DIGIPROD1_TaskChain_MC_HG1510_Validation_TEST_Alan_v1-v1/GEN-SIM-RECO#7abeb498-62b2-11e5-a863-02163e006e3e throug
h DBS.
HTTP Error 409: Da taset not yet inserted by concurrent insert. 
2015-09-24 13:59:02,193:ERROR:DBSUploadPoller:Traceback (most recent call last):
  File "/data/srv/wmagent/v1.0.9.patch2/sw.pre/slc6_amd64_gcc481/cms/wmagent/1.0.9.patch2/lib/python2.6/site-packages/WMComponent/DBS3Buffer/DBSUploadPoller.py", line 114, in uploadWorker
    dbsApi.insertBulkBlock(blockDump = block)
  File "/data/srv/wmagent/v1.0.9.patch2/sw.pre/slc6_amd64_gcc481/cms/dbs3-client/3.2.114/lib/python2.6/site-packages/dbs/apis/dbsClient.py", line 317, in insertBulkBlock
    return self.__callServer("bulkblocks", data=blockDump , callmethod='POST' )
  File "/data/srv/wmagent/v1.0.9.patch2/sw.pre/slc6_amd64_gcc481/cms/dbs3-client/3.2.114/lib/python2.6/site-packages/dbs/apis/dbsClient.py", line 193, in __callServer
    self.__parseForException(http_error)
  File "/data/srv/wmagent/v1.0.9.patch2/sw.pre/slc6_amd64_gcc481/cms/dbs3-client/3.2.114/lib/python2.6/site-packages/dbs/apis/dbsClient.py", line 221, in __parseForException
    raise HTTPError(http_error.url, data['exception'], data['message'], http_error.header, http_error.body)
HTTPError: HTTP Error 409: Da taset not yet inserted by concurrent insert. 
```

It seems a block insert triggers an _internal_ dataset insert in DBS Server, but somehow the block insertion is handled before than the dataset part in dbs server and then it complains back to the client.

Could you please take a look at this issue? It's not as critical as the previous one, since the agent manages to go through in the coming cycles.

**Comment by yuyiguo** [comment] 2015-09-24 14:15
This is a normal error due to new dataset/blocks insert into DB by multiple clients. If you retry, it should go away by itself.

**Comment by amaltaro** [comment] 2015-09-24 14:35
Not sure I got it, are these multiple clients multiple calls coming from dbsClient for the same block? If so, I cannot see it happening from the agent side, since it makes one dbsclient call per block. 

That's why I think it comes from  the server itself and taking a quick look at the code (if I'm not mistaken), it seems a block insertion falls in this part of the code
https://github.com/dmwm/DBS/blob/master/Server/Python/src/dbs/business/DBSBlockInsert.py#L96

which has to add configuration first (?), then dataset and then the block. Do you think there is any way we could guarantee that the dataset will be inserted first (without penalizing performance or etc)? It would be nice to get rid of these errors in the agent side.

**Comment by yuyiguo** [comment] 2015-09-24 16:52
Alan:

This was a wired error. I checked the log files that only one DBS backend vocms0132 has the logs. vocms0133 has empty logs. Why? 

I could not find any DBS access from your test stand around the time 2015-09-24 13:59:02 when you were getting the error. Then I looked at DB database and I found the block was inserted at 2015-09-24  7:00:43 GMT. This is a much earlier time than the time you got the error, I don't why and have no way to find out. I would suggest that you could start a clean test and retest.

**Comment by amaltaro** [comment] 2015-09-24 17:02
About vocms0133, it was decomissioned and vocms0131 took its place now.

About the timestamps, most likely there is a timezone difference here, since this line
2015-09-24 14:00:43,036:INFO:DBSUploadPoller:About to insert block /RelValProdMinBias/CMSSW_7_0_0_pre11-DIGIPROD1_TaskChain_MC_HG1510_Validation_TEST_Alan_v1-v1/GEN-SIM-RECO#7abeb498-62b2-11e5-a863-02163e006e3e

is the second attempt to insert this block, which succeeded, o exactly 7h before (CERN - FNAL timezone :-D).

Anyways, I'm running more tests now and if we hit this problem again, I can update this issue.

**Comment by yuyiguo** [comment] 2015-09-24 17:16
The time I gave is GMT time not FNAL time. Anyway, Let me know how the new tests go.
Thanks for testing.

**Comment by amaltaro** [comment] 2015-09-24 19:24
Just got a new block that failed the first attempt:
```
2015-09-24 20:54:57,280:INFO:DBSUploadPoller:About to insert block /BprimeJetToBZ_M800GeV_Tune4C_13TeV-madgraph-tauola/Integ_Test-ReDigi_cmsRun3_HG1510_Validation_TEST_Alan_v1-v1/AODSIM#fa59d832-62e8-11e5-a863-02163e006e3e
2015-09-24 20:54:57,592:ERROR:DBSUploadPoller:Error trying to process block /BprimeJetToBZ_M800GeV_Tune4C_13TeV-madgraph-tauola/Integ_Test-ReDigi_cmsRun3_HG1510_Validation_TEST_Alan_v1-v1/AODSIM#fa59d832-62e8-11e5-a863-02163e006e3e through DBS.
HTTP Error 409: Da taset not yet inserted by concurrent insert. 
2015-09-24 20:54:57,594:ERROR:DBSUploadPoller:Traceback (most recent call last):
  File "/data/srv/wmagent/v1.0.9.patch2/sw.pre/slc6_amd64_gcc481/cms/wmagent/1.0.9.patch2/lib/python2.6/site-packages/WMComponent/DBS3Buffer/DBSUploadPoller.py", line 114, in uploadWorker
    dbsApi.insertBulkBlock(blockDump = block)
  File "/data/srv/wmagent/v1.0.9.patch2/sw.pre/slc6_amd64_gcc481/cms/dbs3-client/3.2.114/lib/python2.6/site-packages/dbs/apis/dbsClient.py", line 317, in insertBulkBlock
    return self.__callServer("bulkblocks", data=blockDump , callmethod='POST' )
  File "/data/srv/wmagent/v1.0.9.patch2/sw.pre/slc6_amd64_gcc481/cms/dbs3-client/3.2.114/lib/python2.6/site-packages/dbs/apis/dbsClient.py", line 193, in __callServer
    self.__parseForException(http_error)
  File "/data/srv/wmagent/v1.0.9.patch2/sw.pre/slc6_amd64_gcc481/cms/dbs3-client/3.2.114/lib/python2.6/site-packages/dbs/apis/dbsClient.py", line 221, in __parseForException
    raise HTTPError(http_error.url, data['exception'], data['message'], http_error.header, http_error.body)
HTTPError: HTTP Error 409: Da taset not yet inserted by concurrent insert. 

2015-09-24 20:54:58,023:ERROR:DBSUploadPoller:Error found in multiprocess during process of block /BprimeJetToBZ_M800GeV_Tune4C_13TeV-madgraph-tauola/Integ_Test-ReDigi_cmsRun3_HG1510_Validation_TEST_Alan_v1-v1/AODSIM#fa59d832-62e8-11e5-a863-02163e006e3e
```

and then it seems it succeeded at CERN time.
2015-09-24 20:56:40,027:INFO 

You'll see this timestamp minus 7h in the DB logs

**Comment by yuyiguo** [comment] 2015-09-24 20:06
Alan:

I am confused by the time stamp. Which time zone the server log record the access?

The insert failed at 1st try and then success on the second try?

**Comment by yuyiguo** [comment] 2015-09-24 20:52
Yes. The block was inserted into DBS at 20:56:40 CEST. If -7, it should be, it should be 13:56:* in the log files,right? But I did not see the log file had this error. However, I found 20:54:32, the insert failed due to unique constraint on processed dataset insertion. I think this was why the inseration failed. It was two clients competed to insert the same processed dataset at the same time. About two minutes late, the dataset was successfully inserted because the processed dataset was inserted.

INFO:cherrypy.access:[24/Sep/2015:20:54:32] vocms0131.cern.ch 131.225.206.120 "POST /dbs/int/global/DBSWriter/bulkblocks HTTP/1.1" 400 Bad Request [data: - in 186 out 13882 us ] [auth: OK "/DC=com/DC=DigiCert-Grid/O=Open Science Grid/OU=Services/CN=wmagent/cmssrv113.fnal.gov" "" ] [ref: "" "DBSClient/3.2.114/" ]
INFO:cherrypy.access:[24/Sep/2015:20:54:46] vocms0131.cern.ch 127.0.0.1 "GET /dbs/ HTTP/1.1" 200 OK [data: - in 1991 out 576 us ] [auth: OK "" "" ] [ref: "" "ServerMonitor/2.0" ]
ERROR:cherrypy.error:Thu Sep 24 18:54:57 2015 dbsException-conflict-data: Dataset not yet inserted by concurrent insert. (IntegrityError) ORA-00001: unique constraint (CMS_DBS3_INT_GLOBAL_OWNER.TUC_PSDS_PROCESSED_DS_NAME) violated
 'insert all\n           when not exists (select * from cms_dbs3_int_global_owner.processed_datasets where processed_ds_name=processed_n) then\n                into cms_dbs3_int_global_owner.processed_datasets(processed_ds_id, processed_ds_name) values (cms_dbs3_int_global_owner.seq_psds.nextval, processed_n)\n           when not exists (select * from cms_dbs3_int_global_owner.dataset_access_types where dataset_access_type=access_t) then\n                into cms_dbs3_int_global_owner.dataset_access_types(dataset_access_type_id, dataset_access_type) values (cms_dbs3_int_global_owner.seq_dtp.nextval, access_t)\n           when exists (select data_tier_id from cms_dbs3_int_global_owner.data_tiers where data_tier_name=tier) then  \n           into cms_dbs3_int_global_owner.datasets ( dataset_id, dataset, primary_ds_id, processed_ds_id, data_tier_id,\n                           dataset_access_type_id, acquisition_era_id,  processing_era_id,\n                           physics_group_id,  xtcrosssection, prep_id, creation_date, create_by,\n                           last_modification_date, last_modified_by\n                         )\n                  values ( :dataset_id, :dataset, :primary_ds_id,\n                           nvl((select processed_ds_id  from cms_dbs3_int_global_owner.processed_datasets where processed_ds_name=processed_n),\n                                cms_dbs3_int_global_owner.seq_psds.nextval),\n                           (select data_tier_id from cms_dbs3_int_global_owner.data_tiers where data_tier_name=tier),\n                          nvl((select dataset_access_type_id from cms_dbs3_int_global_owner.dataset_access_types where dataset_access_type=access_t), cms_dbs3_int_global_owner.seq_dtp.nextval), \n                           :acquisition_era_id, :processing_era_id, :physics_group_id,\n                           :xtcrosssection, :prep_id, cdate, cby,\n                           :last_modification_date, :last_modified_by \n                         )\n                select  :processed_ds_name processed_n,\n                        :data_tier_name tier,  :dataset_access_type access_t,  \n                        :creation_date cdate, :create_by cby\n                from dual' {'dataset': '/BprimeJetToBZ_M800GeV_Tune4C_13TeV-madgraph-tauola/Integ_Test-ReDigi_cmsRun3_HG1510_Validation_TEST_Alan_v1-v1/AODSIM', 'primary_ds_id': 9127812, 'create_by': 'wmagent@vocms040.cern.ch', 'dataset_access_type': 'PRODUCTION', 'acquisition_era_id': 699837, 'last_modified_by': 'wmagent@vocms040.cern.ch', 'processed_ds_name': 'Integ_Test-ReDigi_cmsRun3_HG1510_Validation_TEST_Alan_v1-v1', 'processing_era_id': 30002, 'xtcrosssection': None, 'last_modification_date': 1443118847, 'physics_group_id': 127, 'dataset_id': 7614519, 'creation_date': 1443118847, 'prep_id': 'ReDigi-cmsRun3', 'data_tier_name': 'AODSIM'}

**Comment by amaltaro** [comment] 2015-09-24 21:08
I don't get these timezones, but for sure my logs and you DB logs have 7h of difference.
I confirm the insertion succeeded at 2015-09-24 20:56:40,027 (+7h your time).

There was no concurrent insert, again single block for this dataset.
Could you try reproducing this issue with the blockdump information I provided you in the other ticket, just fake some values.

I don't have a number, but I would say this failure rate is of 20%, at least.

**Comment by yuyiguo** [comment] 2015-09-24 22:01
OK, Alan, Let's use CEST time only in the discussion.
I checked the DBS, you had three datasets that shared the same processed DS and two of them inserted around the same time. Here are the datasets:

 #1 /BprimeJetToBZ_M800GeV_Tune4C_13TeV-madgraph-tauola/Integ_Test-ReDigi_cmsRun3_HG1510_Validation_TEST_Alan_v1-v1/MINIAODSIM
#2 /BprimeJetToBZ_M800GeV_Tune4C_13TeV-madgraph-tauola/Integ_Test-ReDigi_cmsRun3_HG1510_Validation_TEST_Alan_v1-v1/DQMIO
#3 /BprimeJetToBZ_M800GeV_Tune4C_13TeV-madgraph-tauola/Integ_Test-ReDigi_cmsRun3_HG1510_Validation_TEST_Alan_v1-v1/AODSIM

They all have processed DS: Integ_Test-ReDigi_cmsRun3_HG1510_Validation_TEST_Alan_v1-v1 .
It was not the blocks in the same dataset was trying to insert the processed DS, it is different datasets, but shared the same processed DB and tried to insert the processed DS at the same time.

I was able to insert the block you gave to me in the other issues that you closed it a few hours ago. 
Do you have other data to try?  Or can you just test one dataset at a time?

**Comment by amaltaro** [comment] 2015-09-25 08:46
Ok, this issue is then related to the processed dataset (<FilterName>+ProcessingString+ProcessingVersion).
Do you believe it to be a new issue? My point is that it's quite common to have 2 or more root files in the output of a cmsRun, that means DBS is trying to insert different blocks from different datasets (but the same processed dataset) for quite a long time.
Can't you handle this processed dataset insertion, like if there is one already, then proceed with the block only?

**Comment by yuyiguo** [comment] 2015-09-25 15:03
I don't think this is a new issue. I don't see it took longer to insert a block from my unit tests. All this kind database integrity check/block is access pattern related. it may caused by the tests were trying to insert new processing DS at every dataset. In real case, processed DS usually is not created very often.

In order to speed up entire DBS block insertion, we don't handle individual processed DS before we insert a dataset. That means processed DS is inserted when a dataset is inserted when it  found the required processed DB is not already in DBS. As processed DS usually already in DBS before a dataset is inserted, this is usually not a problem.    

How is your testing going beside this processed DS issue?  I am going to tag another DBS release in order to add the the lumi list split of listFileArray. If nothing from you, I will start to tag, rebuild and retest the new release soon.

**Comment by amaltaro** [comment] 2015-09-25 15:25
I have to check the outcome of the validation, but agent dbs logs are quiet without any issues. So, in principle go ahead with the next tag.

BTW, the access pattern is the same as the last 6 months, and I don't remember seeing these issues before (at least not that often as it currently happens).

**Comment by yuyiguo** [comment] 2015-09-25 15:28
That is strange. Do your code retry after it get this exception?

**Comment by amaltaro** [comment] 2015-09-25 16:11
Yes, and then it succeeds

**Comment by yuyiguo** [comment] 2015-10-27 19:52
@amaltaro 
Did you see this happening again?

**Comment by amaltaro** [comment] 2015-10-28 15:09
Hi Yuyi,

yes, I just got this error again in our testbed agent:
```
2015-10-28 15:59:58,505:INFO:DBSUploadPoller:About to insert block /RelValProdMinBias/DMWM_Test-StepChain_MC_SEs_Validation_TEST_Alan_v1-v1/AODSIM#b0433b94-7d82-11e5-b354-02163e00ed6f
2015-10-28 15:59:58,509:INFO:DBSUploadPoller:About to insert block /RelValProdMinBias/DMWM_Test-StepChain_MC_SEs_Validation_TEST_Alan_v1-v1/GEN-SIM-RECO#ec013140-7d82-11e5-b354-02163e00ed6f
2015-10-28 15:59:58,960:ERROR:DBSUploadPoller:Error trying to process block /RelValProdMinBias/CMSSW_7_0_0_pre11-DIGIPROD1_TaskChain_MC_SEs_Validation_TEST_Alan_v1-v1/AODSIM#ec01e3e2-7d82-11e5-b354-02163e00ed6f thr
ough DBS.
HTTP Error 409: Da taset not yet inserted by concurrent insert. 
2015-10-28 15:59:58,961:ERROR:DBSUploadPoller:Traceback (most recent call last):
  File "/data/srv/wmagent/v1.0.9.patch2/sw.pre/slc6_amd64_gcc481/cms/wmagent/1.0.9.patch2/lib/python2.6/site-packages/WMComponent/DBS3Buffer/DBSUploadPoller.py", line 114, in uploadWorker
    dbsApi.insertBulkBlock(blockDump = block)
  File "/data/srv/wmagent/v1.0.9.patch2/sw.pre/slc6_amd64_gcc481/cms/dbs3-client/3.2.114/lib/python2.6/site-packages/dbs/apis/dbsClient.py", line 317, in insertBulkBlock
    return self.__callServer("bulkblocks", data=blockDump , callmethod='POST' )
  File "/data/srv/wmagent/v1.0.9.patch2/sw.pre/slc6_amd64_gcc481/cms/dbs3-client/3.2.114/lib/python2.6/site-packages/dbs/apis/dbsClient.py", line 193, in __callServer
    self.__parseForException(http_error)
  File "/data/srv/wmagent/v1.0.9.patch2/sw.pre/slc6_amd64_gcc481/cms/dbs3-client/3.2.114/lib/python2.6/site-packages/dbs/apis/dbsClient.py", line 221, in __parseForException
    raise HTTPError(http_error.url, data['exception'], data['message'], http_error.header, http_error.body)
HTTPError: HTTP Error 409: Da taset not yet inserted by concurrent insert. 

2015-10-28 15:59:59,078:ERROR:DBSUploadPoller:Error found in multiprocess during process of block /RelValProdMinBias/CMSSW_7_0_0_pre11-DIGIPROD1_TaskChain_MC_SEs_Validation_TEST_Alan_v1-v1/AODSIM#ec01e3e2-7d82-11e5
-b354-02163e00ed6f
2015-10-28 15:59:59,078:ERROR:DBSUploadPoller:Error trying to process block /RelValProdMinBias/CMSSW_7_0_0_pre11-DIGIPROD1_TaskChain_MC_SEs_Validation_TEST_Alan_v1-v1/AODSIM#ec01e3e2-7d82-11e5-b354-02163e00ed6f thr
ough DBS.
HTTP Error 409: Da taset not yet inserted by concurrent insert. 
2015-10-28 16:01:39,218:INFO:DBSUploadPoller:Starting the DBSUpload Polling Cycle
2015-10-28 16:01:39,220:INFO:DBSUploadPoller:Found 2 open blocks.
2015-10-28 16:01:39,221:INFO:DBSUploadPoller:Loaded blocks: []
2015-10-28 16:01:39,321:INFO:DBSUploadPoller:About to insert block /RelValProdMinBias/CMSSW_7_0_0_pre11-DIGIPROD1_TaskChain_MC_SEs_Validation_TEST_Alan_v1-v1/AODSIM#ec01e3e2-7d82-11e5-b354-02163e00ed6f
```
Not sure whether it makes any difference, but this agent does not have the latest dbsClient version, it's actually a 1.0.9.patch2 WMAgent version.

**Comment by amaltaro** [comment] 2015-10-28 15:10
and as you can see in the logs, the next polling cycle managed to get that block properly inserted in DBS.

**Comment by yuyiguo** [comment] 2015-10-28 18:57
Alan: was this block inserted into cmsweb-testbed?

**Comment by amaltaro** [comment] 2015-10-28 21:42
That's right, it was cmsweb-testbed int/global instance.

**Comment by yuyiguo** [comment] 2015-10-29 15:29
what is the agent's ID/CERT?

**Comment by amaltaro** [comment] 2015-10-29 15:35
replied via email

**Comment by yuyiguo** [comment] 2015-10-29 18:38
OK. Got it. Here is the story:
1. the timestamp(1446043696) in the dataset('/RelValProdMinBias/CMSSW_7_0_0_pre11-DIGIPROD1_TaskChain_MC_SEs_Validation_TEST_Alan_v1-v1/AODSIM') was not DBS timestamp, but the client provided with the DS. So it is not the real insert time. This was very confusing during debugging.
2. The dataset has processed DS : "CMSSW_7_0_0_pre11-DIGIPROD1_TaskChain_MC_SEs_Validation_TEST_Alan_v1-v1/AODSIM"  that was shared with DS "/RelValProdMinBias/CMSSW_7_0_0_pre11-DIGIPROD1_TaskChain_MC_SEs_Validation_TEST_Alan_v1-v1/GEN-SIM-RECO". This is a new processed DS to the DB.
3, The two DS were  inserted into DBS at the exact same time (1446043696).   When a DS is inserted,  DBS will insert processed DS, dataset access type and so on at the same time. When the two DS were inserted, they both found that the new processed DS was not in DBS yet and both tried to insert. Then the second succeeded, the first one failed due to "(IntegrityError) ORA-00001: unique constraint (CMS_DBS3_INT_GLOBAL_OWNER.TUC_PSDS_PROCESSED_DS_NAME) violated". This eventual caused the block "/RelValProdMinBias/CMSSW_7_0_0_pre11-DIGIPROD1_TaskChain_MC_SEs_Validation_TEST_Alan_v1-v1/AODSIM#ec01e3e2-7d82-11e5-b354-02163e00ed6f".
4. There is not much DBS can do on this case, but we can make the error message better for user to understand the problem. Alan ask if DBS can retry the failed block instead of WMagent.  I have put some thoughts on Alan's request and seen two problems: a. To the DBS API that was inserting the failed block, this is only an ORA-00001 error, but nothing else. W/o knowing what exactly caused the ORA-00001 error before retrying, we hesitate to do so.  There are many reasons can generate ORA-00001 and most are not a simple retry can be solved. b. There are 300 s limit post by CMSWEB for any APIs running on CMSWEB. Usually insert block is a time consuming API. We could end up exceeding the time limit before finishing the retry. Then client has to recall the API again anyway. So it is better to start a new API call at the beginning.

**Comment by yuyiguo** [comment] 2015-10-30 21:05
Update the error message to make the error more understandable to client.

**Closed by yuyiguo** 2015-10-30 21:05 UTC

**Comment by amaltaro** [comment] 2015-10-30 21:20
Thanks Yuyi!
