### ISSUE TITLE
Change requirements on checksums

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/DBS#468] opened 2015-04-30 21:37 UTC
Breaking off from here: https://github.com/dmwm/WMCore/pull/5824#issuecomment-97960361 opened by @hufnagel 

It seems to me the fields should have been named crc_checksum, md5_checksum, and adler32_checksum. The requirement should be that *at least* one checksum is supplied. But which checksum(s) are supplied is an operational detail that we have our own rules for. Operationally we've decided that adler32 is best and sufficient *at the current time* so that's what we will supply.

**Comment by yuyiguo** [comment] 2015-05-01 01:51
What currently in checksum is crc?  crc has been the primary checksum in the past? And now we want to use adler32 as the primary one? I am wondering why this was not a problem until now ?

**Comment by PerilousApricot** [comment] 2015-05-01 01:53
Most storage systems provide adler32 and not CRC as their native checksumming, so CRC isn't used nearly everywhere. The I/O load of having to re-read every file just to generate CRC doesn't make sense if nobody is actually using it.

**Comment by ericvaandering** [comment] 2015-05-01 02:46
Right. Tier0 was negatively impacted by having to calculate both so we did a survey to make sure everyone was ok with Adler followed by a decision (a couple of months or so ago) to drop CRC. So unless there is some real reason DBS needs us to, we should make the field optional. If we can't do that, we'll probably fill it with a dummy value. 

We can chat tomorrow if you like.

**Comment by yuyiguo** [comment] 2015-05-01 14:00
The decision of transferring from CRC to Adler was not propagated to DBS.-:(
DBS is still using the traditional CRC  as the required checksum in schedule and code. I will change the schema to be optional to CRC. BTW Adler32 and DM5 are already optional. I will also relax the API too. This will be in June release. Could T0 fake some data for CRC now? Please make the fake data very  obvious.

**Comment by ericvaandering** [comment] 2015-05-01 14:10
Yes, I know. We did not think about DBS needing this data. Is it possible to make one of them, but not a specific one, required? But we may not want that either given the user data review. But it would be good to know.

Alternatively we keep Tier0 calculating both checksums until DBS is ready to drop them. The "emergency" that prompted this discussion is gone; now it is just an optimization. I'll leave that decision up to Dirk and Luis.

**Comment by hufnagel** [comment] 2015-05-01 16:03
Our Tier0 (and I guess also WMAgent) strategy depends a bit on what we do with DBS. I assume here we'll keep all the old CRC checksums and won't delete them from the schema ? If so, I am bit hesitant to just start making up fakes. OTOH, if we decide no one will ever need this checksum and remove them...

Do we have any old data in DBS that has just a CRC checksum and no adler32 checksum ?

**Comment by ericvaandering** [comment] 2015-05-01 16:24
Just on a philosophical level I would oppose removing metadata, even if we think its not going to be used. I'd also not like to make up false metadata just for expediency. The Tier0 has been running at the required scale (?) for months with this extra calculation in place, one more is not going to kill it, IMO.

**Comment by PerilousApricot** [comment] 2015-05-01 16:30
Sorry for the dumb question, but if the I/o is the big problem, couldn't we
just have a script that reads the file once and calculates both checksums?

-- 
Sent from Gmail Mobile

**Comment by yuyiguo** [comment] 2015-05-01 16:45
Yes, we will KEEP all the CRCs in DBS. Deleting data from PROD DBS is not a good idea, IMO. 

There are only 200 files that have only CRC, no adler32 or MD5. In addition, these 200 files are all some sort of test files from the names I see.

**Comment by hufnagel** [comment] 2015-05-01 20:12
Just wanted to bring up teh question, I actually agree with the sentiments raised here. Which means we'll keep calculating the second checksum and hold off on merging this code until we have made the crc checksum optional in DBS. Btw, what I noticed is that we actually pass an md5 checksum 'NOTSET' to DBS, not sure if we are writing this to the DB though. If we do we should probably stop that...

**Comment by hufnagel** [comment] 2015-05-01 20:15
@PerilousApricot , I'll look into it as well. We already do calculate adler32 ourselves by reading the file in python in chunks. If I can use the same chunks to calculate the crc checksum...

**Comment by PerilousApricot** [comment] 2015-05-01 20:18
I use this for some backend phedex stuff @ Vandy, feel free to use/abuse:

```python
#!/usr/bin/env python
"""
    checksummer.py - reads from stdin and returns checksums
"""

import hashlib
import socket
import subprocess
import sys
import time
import zlib

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
#sock.sendto("lfs.checksum.start:1|c", ('brazil.vampire', 8125))

targetFile = None
if len(sys.argv) == 2:
    targetFile = sys.argv[1]

def trimBytes(val):
    prefix = ('B','KB','MB','GB','TB')
    inc = 1
    origVal = val
    for scale in prefix:
        if val < 1024:
            return "%1.2f%s" % (val, scale)
        val = val / 1024.0
    return "%sB" % origVal

adler32 = zlib.adler32("")
cksum = subprocess.Popen("cksum", stdin=subprocess.PIPE,
                                  stdout=subprocess.PIPE)
md5 = hashlib.md5()
sha1 = hashlib.sha1()

blockSize = 1*1024*1024
byteCount = 0
startTime = time.time()
timeCount = 1
statusIncrement = 3
lastBytes = 0
lastTime = time.time()
while 1:
    # read 10 megs at a time
    inputBytes = sys.stdin.read(blockSize)
    if inputBytes == "":
        break
    byteCount += len(inputBytes)
    lastBytes += len(inputBytes)
    adler32 = zlib.adler32(inputBytes,adler32)
    cksum.stdin.write(inputBytes)
    md5.update(inputBytes)
    sha1.update(inputBytes)
    if time.time() - (startTime + timeCount * statusIncrement) > 0:
        currentTime = time.time()
        while currentTime - (startTime + timeCount * statusIncrement) > 0:
            timeCount += 1
        instTime = currentTime - lastTime
        totalTime = currentTime - startTime
        msg = "Inst: %s, %1.2fsec, %s/sec, "
        msg += "Total: %s, %1.2fsec, %s/sec\n"
        sys.stderr.write(msg % (trimBytes(lastBytes), instTime,\
                     trimBytes(lastBytes/instTime),\
                     trimBytes(byteCount), totalTime,\
                     trimBytes(byteCount/totalTime)))
        lastTime = currentTime
        lastBytes = 0

if adler32 < 0:
    adler32 += 2**32
cksumOutput, _ = cksum.communicate()
cksumOutput = cksumOutput.split()[0]
print "md5 %s" % md5.hexdigest()
print "sha1 %s" % sha1.hexdigest()
print "cksum %s" % cksumOutput
adler32Formatted = hex(adler32)[2:10].zfill(8).lower()
print "adler32 %s" % adler32Formatted
print "bytes %s" % byteCount
# construct attribute-setting command line
if targetFile:
    sys.stderr.write('Adding attributes to file %s\n' % targetFile)
    args = ['lio_setattr', '-as', 'user.accre_md5=%s' % md5.hexdigest(),
                        '-as', 'user.accre_sha1=%s' % sha1.hexdigest(),
                        '-as', 'user.accre_cksum=%s' % cksumOutput,
                        '-as', 'user.accre_adler32=%s' % adler32Formatted,
                        '-as', 'user.accre_cksumtime=%s' % time.time(),
                        targetFile]
    print "Executing: %s" % " ".join(args)
    p = subprocess.Popen(args, stdout=subprocess.PIPE,
                               stderr=subprocess.STDOUT)
    out, _ = p.communicate()
    if p.returncode:
        sys.stderr.write("Got an error (%s) setting attributes\n" % p.returncode)
        sys.stderr.write("Output:\n%s\n" % out)
        sys.exit(1)
sys.exit(0)

```

**Comment by hufnagel** [comment] 2015-05-01 20:21
Yeah, that isn't really needed, there is a zlib.crc32() method which I want to try first.

**Comment by PerilousApricot** [comment] 2015-05-01 20:23
The hitch is that crc32() isn't well-defined (different input parameters
are used by different implementations). When I did it, zlib used the wrong
ones and I couldn't get the checksums to match the command line tools. If
you can, though, good luck :)

**Comment by yuyiguo** [comment] 2015-05-01 20:43
@hufnagel , @ticoann 

It looks like T0 and others are writing "NOSET" to MD5. There are 254,080/4,953,5462 files do not have "NOSET" MD5. So most of files have "NOSET" in MD5. Please stop writing it.

**Comment by hufnagel** [comment] 2015-05-01 20:46
I am going to rework the patch anyways, let me tackle this as well. Once we have done this, as this is clearly not a correct checksum, maybe we should then do a cleanup campaign at least for the wrongly set MD5 checksums...

**Comment by hufnagel** [comment] 2015-05-01 22:01
After reading up a bit on CRC checksums, its pretty much hopeless to reproduce what cksum produces in python. Almost all the usual CRC32 algorithms implement the zlib CRC32 checksum, which is different. Going to call a subprocess like your example instead.

**Comment by hufnagel** [comment] 2015-05-01 22:12
Btw, this would mean no changes needed in DBS, stay tuned...

**Comment by hufnagel** [comment] 2015-05-02 14:56
See  [https://github.com/dmwm/WMCore/pull/5855](dmwm/WMCore#5855)

@ericvaandering , should we close this and leave things as they are ? Or should we still change it (with lower priority) and make either adler32 mandatory or one of adler32/crc mandatory ? Arguably adler32 is actually way more important than crc...

**Comment by PerilousApricot** [comment] 2015-05-02 14:58
WMCore#5855 (test)

**Comment by ericvaandering** [comment] 2015-05-02 15:26
Sorry, saw the other bug before hand. I think we'd like to clean this up removing a checksum that no one uses and produces kind of ugly code in the patch.

From the DBS side, I would like to make "a checksum" mandatory and we all agree that adler32 is what we provide. But I don't want to encode adler32 as a requirement in DBS. As soon as we do, we will move again. :-)

**Comment by ericvaandering** [comment] 2015-05-02 16:14
I want to move forward on this change regardless of what WMAgent supplies. It just makes sense to me.

**Comment by yuyiguo** [comment] 2015-05-02 17:23
These all sounds good to me. I'd like to wait a bit for Stefano's common on user data. If user data will provide any formate of checksum, DBS will ask one of the three checksums, but open for the data provider to decide which one they will use.

**Comment by hufnagel** [comment] 2015-05-02 17:47
Well, if it's user data from CRAB3, we should make sure to provide the same as we do from WMAgent...

**Comment by yuyiguo** [comment] 2015-05-03 13:09
I agreed @hufnagel . Let's see what @belforte says. Would you please common on user data checksum,  @belforte ?

**Comment by ericvaandering** [comment] 2015-05-03 13:16
I'm confused. In Slack @belforte  has said that they will supply a checksum, likely adler32, and agrees that DBS should not enforce any particular one, but can enforce that A checksum is provided.

**Comment by belforte** [comment] 2015-05-03 17:00
I think we agree.  DBS should require a checksum, but does not decide which one. This gives us some flexibility while still trying to use Adler 32 everywhere

**Comment by yuyiguo** [comment] 2015-05-04 02:53
Sounds good. I will update the schema to remove the NOT NULL on  checksum and the API to require one type of checksum to be provided. This will be in June release.

**Comment by ericvaandering** [comment] 2015-05-04 06:46
As long as you were planning a June release anyhow. You wanted to skip one, but that was May, correct? With our workarounds, there is no urgency to this request.

**Comment by yuyiguo** [comment] 2015-05-04 14:56
Yes, the skipped one is May. Diego is deploying May release today. The June one is my target. I will work on it soon for June release. I have some other issues to fix in the June release too.

**Comment by yuyiguo** [comment] 2015-05-18 15:59
@belforte 

I just want to make sure you and crab developers are aware of this change. DBS will no longer enforce check_sum requirement instead we require one of the "check_sum", "adler32" or "MD5" should be presented when inserting a file. DBS will no longer provide default values for any of the check sums. DBS will check if one of the three check sums is in the data. If not, DBS will throw DBS missing data exception. 

This change will be in June release.

**Comment by yuyiguo** [comment] 2015-05-18 16:25
Done with code change and unit tests, as well as scripts for schema changes.

**Comment by mmascher** [comment] 2015-05-19 07:25
Hi Yuyi, this should be all right in CRAB3. I imagine that as of wednesday we can check this by chosing to publish in cmsweb-testbed instead of cmsweb, right? We will verify that everything is all right in the tests related to this cycle (note for @jmarra13 and @juztas)

**Comment by yuyiguo** [comment] 2015-05-26 21:13
@mmascher 
@belforte 
@ticoann 
@amaltaro 
@jmarra13 
@juztas 
@hufnagel 

Hi, Everyone:

The new server is running on cmsweb-testbed. In this server dbs server will not insert the data tier for the client if it is not already in DBS and the block insert will be failed. DBS will not require check_sum to be present when insert block/files, however, it will require at least one of the check sum types is in the input data. I have removed any default values for any types of check sum.

The server version is DBS_3_2_11a, but I had some bug in the client so I tagged DBS_3_2_11b. I tested 11b client against 11a server and all tests passed. Would you please test your code ASAP and let me know your result? I knew crab gets DBS client from github directly. Does WMA need a new rpm for the client? If so, is my private build OK or I have to ask Diego for a new official rpm?

**Comment by belforte** [comment] 2015-05-26 21:21
Sorry, I have not understood.
Do we have to update the client ? before then server is updated ?
or can we use new server with current client and deal independently
with client upgrade ?

**Comment by hufnagel** [comment] 2015-05-26 21:23
The new server has relaxed requirements compared to the old one. Old clients should just work, but of course should be tested as always.

What we really would need to test is new client functionality (for instance only passing adler32 and not cksum anymore), but AFAIK for the moment we don't really plan to do this at least on the WMAgent side. With my patch merged we basically get the cksum for free anyways...

**Comment by yuyiguo** [comment] 2015-05-27 14:03
@belforte 
@hufnagel 
Old client works with new server. You don't have to change the client if you don't make a call with long list of lfn, lumi or run. WMA needs new client if it drops the split calls by itself.    

Client API does not enforce any of the check sums. It is the server taking care it. As long as you have one type of check sum, it will be OK.

**Comment by belforte** [comment] 2015-05-27 14:46
thanks Yuyi

**Comment by yuyiguo** [comment] 2015-07-09 19:54
Done.

**Closed by yuyiguo** 2015-07-09 19:54 UTC
