### ISSUE TITLE
ListFiles call doesn't work with a big lumi list

### ISSUE THREAD

**Issue by julianbadillo** [dmwm/DBS#462] opened 2015-03-18 13:49 UTC
On:
https://github.com/dmwm/DBS/blob/master/Client/src/python/dbs/apis/dbsClient.py#L867

When listFiles is called with a big list of lumis (we tried with 100), the call fails with an error like:
RestClient.ErrorHandling.RestClientExceptions.HTTPError: HTTP Error 414: Request-URI Too Long

This because the call is done in a GET method, therefore the lumi-list is encoded in the request URI.
A similar behaviour happens in every other list method that allows list as inputs, such as:
https://github.com/dmwm/DBS/blob/master/Client/src/python/dbs/apis/dbsClient.py#L531
When block_name is provided as a list (and has several blocks)

@ticoann @amaltaro

**Comment by yuyiguo** [comment] 2015-03-20 14:02
@julianbadillo 
@amaltaro 
@ticoann 

This request was done in last release (Feb) as requested by Seangchan. check listFileArray API for what you need. Also, could you give me the query that has 100+ lumi sections?

**Comment by ticoann** [comment] 2015-03-20 14:07
Hi Yuyi, as we discussed could you remove listFileArray, and just keep listFile api? That way we don't have 2 APIs doing the same thing.

**Comment by yuyiguo** [comment] 2015-03-20 14:12
When we move to Lasi's REST api, all queries have to use GET, POST is not supported for query. To reduce redoing things in the future and now, I'd like to ask you guys try what is already there.

**Comment by ticoann** [comment] 2015-03-20 14:17
It is just added last deployment and no one is using that yet. My point is there are 2 apis doing the same thing with one has super set of other api (allows list of lfn). It seems cleaner that dbs provide just one client api. Unless there is techincal difficulties to do that.

**Comment by amaltaro** [comment] 2015-03-20 14:21
Yuyi, if it was made in Feb release, why is it not in production then?
Can you check the DBS logs? Look for 414 and you will find that query (from 2 or 3 days ago).
Otherwise let me know.

**Comment by julianbadillo** [comment] 2015-03-20 14:24
@ticoann @yuyiguo I think we could use either any of those two api's. As long as it supports the lumiList call
I fail to see the api documentation for listFilesArray, though, I was looking here:
https://cms-http-group.web.cern.ch/cms-http-group/apidoc/dbs3-client/current/dbs.apis.html
The query we were trying to do is this one:
https://cmsweb.cern.ch/couchdb/reqmgr_workload_cache/alahiff_HCA-Fall14DR73-00003_00007_v0__150318_074242_9537
So it actually has ~1400 lumis.

**Comment by ticoann** [comment] 2015-03-20 14:27
Julian, Alan, listFileArray is added for other reason (allowing multiple lfns as input) for my request. Yesterday, we looked at the code and it seems since it is using POST call it can be used for lumi case as well.  However it seems that we don't need to keep but listFileArray and listFile api. since it is basically doing the same thing. So I suggested that we rename listFileArray to listFile. (which means client uses only POST call). I thought Yuyi agreed. But she might found it is not that simple. (Yuyi, is that the case?)

**Comment by yuyiguo** [comment] 2015-03-20 14:30
@amaltaro  I am confused you question. I was able to call listFileArray API against cmsweb.
@julianbadillo  thanks for the query. I will try it.  DBS use automatically generate doc when the new APIs added to the release. Some how the cmsweb building system no longer to do so. I need to figure out why. This is on my to-do list. Sorry about the doc confusing.

**Comment by yuyiguo** [comment] 2015-03-20 14:32
@ticoann I'd like we try what already in the production instead of changing for little things and will change back in the future. I understand your point, but can we try what we have now?

**Comment by amaltaro** [comment] 2015-03-20 14:39
Sorry, I got confused. The easiest way would be to completely migrate the WMCore code to listFileArray then. However, if you foresee its retirement in the next months, we better not do that.

**Comment by ticoann** [comment] 2015-03-20 14:41
@yuyiguo, If we can fix it right now, we will try what we have. 
But the case is we have to fix it and wait for the cmsweb deploy to take an effect. So there is no advantage of doing fix in WMCore code other then doing DBS side. (I know it is more trouble for you to change and running the test).  
However, since we are still in testbed case, I think correct solution is making one api in DBS. 
If it is too complicated, it might not be good. Yesterday, when we looked at it is the simple change. 
So I suggested that way.

**Comment by yuyiguo** [comment] 2015-03-20 14:52
@amaltaro client API listFileArray will not retired, 

@ticoann Can we use what we have?

**Comment by yuyiguo** [comment] 2015-03-20 14:58
@julianbadillo when you call file api, do you use detail=1?

**Comment by ticoann** [comment] 2015-03-20 15:23
@yuyi If you insist, I will change our code. (I thought it is a just cleaner solution to have just one api doing the same thing (no one is using the second api) and change is simple like this.
https://github.com/dmwm/DBS/commit/f942371f31f9210de5cbd3e89c2ec25a0601c1cb

Alan, I will take care of the issue. Thanks,
https://github.com/dmwm/WMCore/issues/5698

**Comment by yuyiguo** [comment] 2015-03-20 16:10
@ticoann you may want to hold to change any wmcore code. I am testing the 1000+ lumi list now. There are repeated lumi numbers in the list by just scanning it by eyes.

**Comment by ticoann** [comment] 2015-03-20 16:27
@yuyiguo, change are already made. 
https://github.com/dmwm/WMCore/pull/5699
Just let me know when test is done.

**Comment by yuyiguo** [comment] 2015-03-20 16:32
Let me know do you need detail=1 or not?

**Comment by ticoann** [comment] 2015-03-20 16:41
detail = 1 is needed.

**Comment by yuyiguo** [comment] 2015-03-20 17:14
Oracle error:
DatabaseError: (DatabaseError) ORA-01795: maximum number of expressions in a list is 1000

**Comment by ticoann** [comment] 2015-03-20 17:47
Let do this then,  I will push in Alan's temporary path for this release. https://github.com/dmwm/WMCore/pull/5692. 
For next deployment (May),  If Yuyi can handle Oracle code in DBS Server side, that is great. If not we will just make Alan's temp code permanently.

**Comment by yuyiguo** [comment] 2015-03-20 17:59
Can you hold it a bit? I will try to make a new release in April. Is it too late to request a cmsweb testbed deployment today or Monday?

**Comment by ticoann** [comment] 2015-03-20 18:24
It is not too late. Just let me know. To be clear, we are changing all listFiles calls in WMCore to listFileArray which expect to get the same result, correct?

**Comment by ticoann** [comment] 2015-03-20 18:25
But it is too hassle to validate, we don't have to hurry and push it. We can use Alan's patch for now.

**Comment by yuyiguo** [comment] 2015-03-20 18:45
The result is the same. Why you change all the listFiles calls to listFileArray? You only need it when you have long list of lumi or lfn. How you get the lumi list that passed to DBS? Can you cleanup the list to have unique lumi number instead of repeated ones?

**Comment by ticoann** [comment] 2015-03-20 20:16
If the api can handling both small number of lfns (lumis) and long number of lfns(lumis) why should we use two different one instead one which handling both?

**Comment by yuyiguo** [comment] 2015-03-20 21:07
It is up to you if you want to change, but it is not necessary.

**Comment by ticoann** [comment] 2015-03-20 21:35
It is easier for us to use one api throughout instead of checking whether it might have long list of input every time api calls. My only concern is whether 2 apis returns the same thing, but you already clarify that. Actually it is no trouble putting Alan's patch now and change it later. If you need to work over the weekend. I will won't be around Monday and Tuesday. Just let me know.

**Comment by yuyiguo** [comment] 2015-03-20 21:45
It is major sql change. I just got the code done, but did not run smoothly. -:(
Even if I got it done this weekend, it will require heavy tests and new unit tests have to be added,

**Comment by ticoann** [comment] 2015-03-20 21:49
Yuyi, then don't worry about it. we will just put Alan's patch first. That won't be a problem for us and you can put the Oracle change for May deployment. Not worth using your weekend for that. Thanks,

**Comment by yuyiguo** [comment] 2015-05-13 16:42
@julianbadillo 

You opened this issue because you could not call listFiles(https://github.com/dmwm/DBS/blob/master/Client/src/python/dbs/apis/dbsClient.py#L867) with a long lumi list .
Or could not call listBlockSummaries (https://github.com/dmwm/DBS/blob/master/Client/src/python/dbs/apis/dbsClient.py#L531) with a long blcok_name list.

I was able to repeat  the error you got from listFiles call and it will be fixed in next release. However, the listBlockSummaries is already splited call if a long block_name list is received. I could not reproduce the "HTTP Error 414: Request-URI Too Long" . Could you please give me the DBS query you used to generate the error if you can dig it out?

**Comment by yuyiguo** [comment] 2015-07-09 21:02
Done.

**Closed by yuyiguo** 2015-07-09 21:02 UTC
