### ISSUE TITLE
HTTPError: HTTP Error 400: DBSMigration: ENQUEUEING_FAILED.

### ISSUE THREAD

**Issue by juztas** [dmwm/DBS#453] opened 2015-02-10 08:58 UTC
More information here: https://github.com/dmwm/AsyncStageout/issues/4335#issuecomment-73663717

**Comment by yuyiguo** [comment] 2015-02-19 16:04
@juztas 
@HassenRiahi 
@belforte 

I was able to reproduce the error using your code(*) on phys03. However, this is the production system and I cannot really debug the problem. So I tried to migrate the very same dataset to my VM and everything went fine.  I compared my VM with phys03. My VM has no parents or grandparents of the dataset. So I initially imported 2+5+22+99 blocks from prod for all the parents of this dataset. Then I removed the top dataset and its blocks from my VM to simulate the phys03. My migration was again successful. I am thinking it might be something wrong with the parent blocks in the phys03, but I cannot debug it because it is production.

Do you have any ideas about the data in phys03 related to this dataset? 
Thanks,
yuyi
 

( * )

import logging
import dbs.apis.dbsClient as dbsClient
import os

proxy = os.environ.get("SOCKS5_PROXY")
migrateURL="https://cmsweb.cern.ch/dbs/prod/phys03/DBSMigrate"
migrateApi = dbsClient.DbsApi(url=migrateURL, proxy=proxy)
data = {'migration_input': '/JetHT/StoreResults-Run2012D_22Jan2013_TLBSM_53x_0161496fccaa0bf55fbb525b618345b5-v1/USER', 'migration_url': 'https://cmsweb.cern.ch/dbs/prod/global/DBSReader/'}
result = migrateApi.submitMigration(data)
status = migrateApi.statusMigration(dataset='/JetHT/StoreResults-Run2012D_22Jan2013_TLBSM_53x_0161496fccaa0bf55fbb525b618345b5-v1/USER')
print status

**Comment by belforte** [comment] 2015-02-19 16:22
no good idea.
Does migration server log offer any more info then ENQUEING_FAILED ?
In case of need I think we can restart migration server with
more diagnostics, a brief outage should be transparent.
I do not really know how migration sever is connected.

Maybe some of those parents had already migrated to phys03
but somehow got corrupted ? Would explain why all is OK when
you do a fresh migration from global.

**Comment by yuyiguo** [comment] 2015-02-19 17:31
This migration never started on phys03 because the request cannot pass validation and be registered. There are 4 production servers in prod and to register this migration there are a lot of DB calls to verify and compare the source and destination DB. I am chasing these calls now.

**Comment by yuyiguo** [comment] 2015-02-24 03:41
@juztas 
@HassenRiahi 
@belforte
I migrated the dataset for you, please check it.
This was a complicated case. The dataset requested to be migrated has three layers of parents/grand parents/great grandparents. The two low level parents were already in phys03 before the migration. However the highest parent/great grandparent dataset were partially in phys03. There are 540 blocks for this dataset in prod. Among these 540 blocks 218 blocks were already in phys03 before the migration. I guess the 218 blocks was brought to phys03 by block migration. The rest 322 blocks were not actually parents of any of these migrated blocks so they were not migrated to phys03 when using block migration. However, when we use dataset migration, all blocks under the dataset will be migrated no mater they are parents or not. The migration request server was expected a full line of migration, but the middle layers was missing in this case because they already in phys03. So the request server did not know how to handle this and failed. I changed my VM to handle this user case properly and migrated it using my VM connecting to phys03 for migration request server. I will fix this in prod for Match release.

**Comment by belforte** [comment] 2015-02-24 06:50
xie xie Yuyi.
Do you see reasons for Crab3 to give up calling the
migrate_dataset API ?
By the way IIUC there are a few more datasets in this situation,
shall we assume that simply repeating the migration with the
March release of DBS will do ?

**Comment by dan131riley** [comment] 2015-02-24 14:19
It's also possible blocks were added to the highest parent
after the initial migration, as can happen with RAW data.
With DBS2 (this looks like DBS2 era data), we rewrote the
migration code to do a block-by-block check of the parents.

-dan

**Comment by yuyiguo** [comment] 2015-02-24 15:15
Stefano:
There is no needs to stop dataset migration. The new release should fix the problem. Please resubmit it after March release.

Dan:

I handled the use case that new blocks added to top level dataset and no child dataset/blocks generated from the added blocks. So the migration server should handle this now. Let's see and I will keep an eye on this.

**Comment by yuyiguo** [comment] 2015-02-27 20:24
Fixed in DBS 3.2.9/

**Closed by yuyiguo** 2015-02-27 20:24 UTC
