### ISSUE TITLE
num_events/num_files is multiplicated for dataset when searching with 2nd key

### ISSUE THREAD

**Issue by anorkus** [dmwm/DBS#539] opened 2017-02-09 10:20 UTC
Hi,

if i do filesummary on dataset:
https://cmsweb.cern.ch/dbs/prod/global/DBSReader/filesummaries?dataset=/SingleMuon/Run2016B-23Sep2016-v3/AOD
i get normal numbers, but if i iterate and sum all the runs of dataset and query:
https://cmsweb.cern.ch/dbs/prod/global/DBSReader/filesummaries?dataset=/SingleMuon/Run2016B-23Sep2016-v3/AOD&run_num=273150
the sum is 400M -> 2.5 more events then the summary page without 2nd parameter.
main issue is the second part of the sql query:
https://github.com/dmwm/DBS/blob/9b5fdb8ae4f95ec39e63dcf4bc2485c8d6e7f338/Server/Python/src/dbs/dao/Oracle/File/SummaryList.py#L149

and the fact the single file has multiple runs, so the num_events of this file will be returned for each run.

same issue with number of files when doing a multiple search. In summary page the number of files is 8325, and if i loop over runs and sum them up result is num_files:21045

same applies to files list api: summing up will return hyperbolised number_of_*  for dataset where file can contain multiple runs.

**Comment by yuyiguo** [comment] 2017-02-09 20:54
@anorkus , Thanks for reporting this. I will fix it by adding the unique constraint on the file ids. I thought that it was always one run per file.  I understood now that the files generated by production is one run per file, not all the files like this way as I talked with Eric. Of course, your data proved a file may have more than one runs.
I will have it fix in next release.

**Comment by yuyiguo** [comment] 2017-02-16 17:28
@anorkus Looking into this in details I found we could not fix it just only from DBS side. DBS was designed for single run per file and we don't have the number of events per run if there are multiple runs in a file. I have discussed this with Eric and Chris. The idea case is that DBS adding events per lumi into the DB, but we need to check if frame work can get this info into DBS.  

In order to finally report correct events of per run for a file that has multiple runs, it will involve the data producer too. I will update this issue when I have more on this. For now, I would suggest you don't query  by individual runs.

**Comment by ericvaandering** [comment] 2017-02-16 21:27
Let me put in my two cents: summing nEvent by run is a reasonable and we should be able to address this with some deep changes to all our tools. 

The second query you describe Sum(nFiles(run)) should not be expected to return number of files as long as the convention of one run per file is violated.

**Comment by franzoni** [comment] 2017-03-03 06:23
hello @yuyiguo @ericvaandering 
do you have updates on this matter ? Can you provide an eta ?
Thanks!

**Comment by ericvaandering** [comment] 2017-03-03 13:38
No ETA yet. Changing this means changing almost every bit of software in O&C including CMSSW. And even once that’s done, it won’t be available for data already written. We’re working on plan to address this, though.

Eric

**Comment by sextonkennedy** [comment] 2017-03-15 20:09
@anorkus, @franzoni Is it possible to change the query so that it is done like Dima does, and avoid this issue?  While the campaign was progressing I used that plot to report to the XEB instead of the pMp historic plot because the event counts were correct.  As Eric says this change will be a while…

**Comment by franzoni** [comment] 2017-03-18 07:03
hello @sextonkennedy , what does "Dima" do ? 
Revert to the RAW parents ?

**Comment by hufnagel** [comment] 2017-03-20 06:21
listFileSummaries  gives you information for files only. You can restrict to files belonging to certain runs, but you still get file level information, not run level information, hence you also get files where only part of the file belongs to a certain run. That's all fine, I don't think anyone wants to change anything.

At the same time, this gives file level information and as such, it should return the full run/lumi/event map for the file, shouldn't it ? Like it returns the run/lumi content now we just expand that.

Given that, DAS has all the knowledge about what's in the file and any kind of aggregation and remapping of that information into a run or lumi context can happen within DAS.

What I don't see here is where there is a need for a new DBS API. If DAS already has all the information, why do we need another DBS API ? Do we foresee a use case where someone asks for run/lumi specific aggregate numbers where we would not expand this and pull fully detailed dataset/block/file info from DBS ?

**Comment by sextonkennedy** [comment] 2017-03-21 16:04
Dirk confirmed that the answer is yes, he is using the parent information which will not have more then 1 run per file since it is RAW data.

**Comment by franzoni** [comment] 2017-04-04 07:46
Thanks @sextonkennedy for the confirmation.

@ericvaandering , during the S&C meeting on Friday March 31st,
you reported that work is ongoing to fix the behavior for number of events per run.
That's good news - on what time scale do you expect this work to be completed ?

Depending on the time necessary, we'll evaluate if/which temporary solution to put in place.

Thanks!

**Comment by ericvaandering** [comment] 2017-04-04 08:05
I'm hoping that we can have the pieces in place for the 2017 physics collision data. If not then, shortly after. 

But of course, that will only help you with new data produced (data or MC) and won't do anything for the PB of data already tracked in DBS. If you want this level of info on those data, your temporary solution will need to be semi-permanent.

**Comment by ericvaandering** [comment] 2017-04-04 08:09
@franzoni see above (just tagging you)

**Comment by franzoni** [comment] 2017-06-26 19:03
Hello

is this message from @hufnagel https://hypernews.cern.ch/HyperNews/CMS/get/tier0-Ops/1647/2.html relating to the solution of this issue?  

Cheers, G.

**Comment by ericvaandering** [comment] 2017-06-27 15:12
Yes, both Tier0 and WMAgent updates that start to populate this info should be rolling into production in the next week or two. 

Of course, this doesn't change anything for older datasets, but at least we will have it going forward. CRAB will follow with the July release, as I understand it.

**Comment by franzoni** [comment] 2017-07-04 20:31
Brilliant!

Will you announce the deployment? We have an immediate use case for employment/testing of the newly added info.

**Comment by ericvaandering** [comment] 2017-07-05 14:36
Yeah, we'll announce. Maybe next week when Yuyi is back from vacation and we have some example data to show people.

**Comment by ericvaandering** [comment] 2017-07-21 18:00
Announced: 

https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/3081.html

@yuyiguo can we close this issue?

**Closed** 2017-07-21 18:03 UTC
